---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
library(janitor)
library(here)
library(readr)
library(readxl)
```

```{r}
# check location of working directory
here()
```

** Read files **

```{r}
candy_2015 <- read_excel("../raw_data/boing-boing-candy-2015.xlsx")
candy_2016 <- read_excel("../raw_data/boing-boing-candy-2016.xlsx")
candy_2017 <- read_excel("../raw_data/boing-boing-candy-2017.xlsx")
```

```{r}
# view the raw data
#view(candy_2015)
#view(candy_2016)
#view(candy_2017)
```

** Select required columns **

```{r}
# select required columns by position (column numbers)
candy_2015_clean <- candy_2015 %>%
  select(c(2:96))
```
```{r}
# select required columns by position (column numbers)
candy_2016_clean <- candy_2016 %>%
  select(c(2:5,7:106))
```
```{r}
# select required columns by position (column numbers)
candy_2017_clean <- candy_2017 %>%
  select(c(2:5,7:109))
```

** Clean column names **

```{r}
# clean the column names
candy_2015_clean <- clean_names(candy_2015_clean)
candy_2016_clean <- clean_names(candy_2016_clean)
candy_2017_clean <- clean_names(candy_2017_clean)
```

** Add new columns **

```{r}
# add new column called year and insert value for each row
candy_2015_clean$year = "2015"
candy_2016_clean$year = "2016"
candy_2017_clean$year = "2017"

# add missing columns to 2015, with no values
candy_2015_clean$country = ''
candy_2015_clean$gender = ''
```

** Reorder 2015 columns to match 2016/2017 **

```{r}
# reorder 2015 columns to match column order of 2016/2017
candy_2015_clean_reordered <- candy_2015_clean[, c(2, 98, 1, 97, 3:96)]
```

** Pivot long each data set **

```{r}
dim(candy_2015_clean_reordered)
dim(candy_2016_clean)
dim(candy_2017_clean)
```

```{r}
# pivot_long each data set
candy_2015_clean_vertical <- pivot_longer(data = candy_2015_clean_reordered[,1:98],
             cols = 5:97,
             names_to = "candy",
             values_to = "rating")

candy_2016_clean_vertical <- pivot_longer(data = candy_2016_clean[,1:105],
             cols = 5:104,
             names_to = "candy",
             values_to = "rating")

candy_2017_clean_vertical <- pivot_longer(data = candy_2017_clean[,1:108],
             cols = 5:107,
             names_to = "candy",
             values_to = "rating")
```

** Rename columns to prepare for row binding **

```{r}
colnames(candy_2015_clean_vertical)[1] <- "trick_or_treating"
colnames(candy_2015_clean_vertical)[2] <- "gender"
colnames(candy_2015_clean_vertical)[3] <- "age"
colnames(candy_2015_clean_vertical)[4] <- "country"
colnames(candy_2015_clean_vertical)[5] <- "year"

colnames(candy_2016_clean_vertical)[1] <- "trick_or_treating"
colnames(candy_2016_clean_vertical)[2] <- "gender"
colnames(candy_2016_clean_vertical)[3] <- "age"
colnames(candy_2016_clean_vertical)[4] <- "country"
colnames(candy_2016_clean_vertical)[5] <- "year"

colnames(candy_2017_clean_vertical)[1] <- "trick_or_treating"
colnames(candy_2017_clean_vertical)[2] <- "gender"
colnames(candy_2017_clean_vertical)[3] <- "age"
colnames(candy_2017_clean_vertical)[4] <- "country"
colnames(candy_2017_clean_vertical)[5] <- "year"
```

** Row bind all data sets into a single data set **

```{r}
candy_all_years_clean <- rbind(candy_2015_clean_vertical,
                               candy_2016_clean_vertical,
                               candy_2017_clean_vertical)
```

** Lower case all chr values **

```{r}
# lowercase all chr values
candy_all_years_clean <- candy_all_years_clean %>%
  mutate(trick_or_treating = tolower(trick_or_treating)) %>%
  mutate(gender = tolower(gender)) %>%
  mutate(country = tolower(country)) %>%
  mutate(candy = tolower(candy)) %>%
  mutate(rating = tolower(rating))
```

** Remove invalid ages (assume age range 10-99) **

```{r}
# remove invalid ages from age column
age_pattern <- "[1-9][0-9]" # ages 10-99 only

candy_all_years_clean$age <- candy_all_years_clean$age %>%
  str_extract(age_pattern)
```

** Convert age column from chr to dbl data type **

```{r}
# convert age to numeric
candy_all_years_clean$age <- as.numeric(candy_all_years_clean$age)
```

```{r}
# check age column for values
#table(candy_all_years_clean$age)
```

** clean country column **

```{r}
# check country column for values before cleaning
#unique(candy_all_years_clean$country)
```

```{r}
# clean country column
invalid_canada <- c("canada`", "can")
invalid_usa <- c("united states of america", "united states", "ussa", "u.s.a", "murica", "usa!",
                 "usa (i think but it's an election year so who can really tell)", "u.s.",
                 "america", "units states", "usa usa usa", "usa! usa! usa!", "the best one - usa",
                 "the yoo ess of aaayyyyyy", "usa!!!!!!", "usa! usa!", "united sates",
                 "sub-canadian north america... 'merica", "trumpistan", "merica", "united stetes",
                 "usa usa usa usa", "united  states of america", "united state", "united staes",
                 "usausausa", "unhinged states", "us of a", "unites states", "the united states",
                 "north carolina", "unied states", "u s", "the united states of america",
                 "unite states", "insanity lately", "usa? hard to tell anymore..", "'merica",
                 "usas", "pittsburgh", "new york", "california",
                 "i pretend to be from canada, but i am really from the united states.",
                 "united stated", "ahem....amerca", "ud", "new jersey", "united ststes",
                 "united statss", "murrika", "usaa", "alaska", "n. america", "u s a",
                 "united statea", "usa usa usa!!!!", "u.s.a.", "us")
invalid_uk <- c("england", "united kingdom", "united kindom", "u.k.", "scotland", "endland")

candy_all_years_clean <- candy_all_years_clean %>%
  mutate(
    country = ifelse(country %in% invalid_canada, "canada", country),
    country = ifelse(country %in% invalid_usa, "usa", country),
    country = ifelse(country %in% invalid_uk, "uk", country)
    )
```

```{r}
# check country column for values after cleaning
unique(candy_all_years_clean$country)
```

** Write clean data to CSV **

```{r}
# write clean data set to CSV
write_csv(candy_all_years_clean, "../clean_data/boing_boing_candy_clean.csv")
```

