---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
library(janitor)
library(here)
```

```{r}
here()
```


```{r}
decathlon <- read_rds(here("raw_data/decathlon.rds"))
decathlon
```

```{r}
glimpse(decathlon)
view(decathlon)
```

```{r}
# convert row names to a column
decathlon <- rownames_to_column(decathlon, "name")
```


```{r}
# tidy column names
decathlon_clean <- clean_names(decathlon)

decathlon_clean
```

```{r}
# convert wide data to long data
decathlon_clean <- decathlon_clean %>%
  pivot_longer(cols = "x100m":"x1500m",
               names_to = "event",
               values_to = "result")
decathlon_clean
```
Q1: Who had the longest long jump seen in the data?

```{r}
q1 <- decathlon_clean %>%
  filter(event == "long_jump") %>%
  arrange(desc(result)) %>%
  head(1)
q1
```

Q2: What was the average 100m time in each competition?

```{r}
q2 <- decathlon_clean %>%
  select("competition", "event", "result") %>%
  filter(event == "x100m") %>%
  group_by(competition) %>%
  summarise(average_result = mean(result))
q2
```