---
title: "R Notebook"
output: html_notebook
---

** load libraries **

```{r}
library(tidyverse)
library(dplyr)
library(janitor)
library(here)
library(readr)
library(readxl)
```

** read cleaned data file **

```{r}
# gender and country need to be defined col_type
candy <- read_csv("../clean_data/boing_boing_candy_clean.csv",
                  col_types = cols(gender = col_character(), country = col_character()))
```

** review data **

```{r}
dim(candy)
```

```{r}
glimpse(candy)
```

 ** TASK QUESTIONS **
 
Q1: What is the total number of candy ratings given across the three years. (number of candy ratings, not number of raters. Don’t count missing values)

```{r}
total_candy_ratings <- candy %>%
  select(rating) %>%
  filter(rating == "joy" | rating == "despair" | rating == "meh") %>%
  summarise(total_ratings = n())
total_candy_ratings
```

Q2: What was the average age of people who are going out trick or treating and the average age of people not going trick or treating?

```{r}
average_age_going_out <- candy %>%
  select(age, trick_or_treating) %>%
  filter(trick_or_treating == "yes", age != "NA") %>%
  summarise(average_age_going_out = mean(age))
average_age_going_out

average_age_not_going_out <- candy %>%
  select(age, trick_or_treating) %>%
  filter(trick_or_treating == "no", age != "NA") %>%
  summarise(average_age_not_going_out = mean(age))
average_age_not_going_out
```

